[2023-01-03T19:16:58.447+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:05:54.497116+00:00 [queued]>
[2023-01-03T19:16:58.463+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:05:54.497116+00:00 [queued]>
[2023-01-03T19:16:58.464+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:16:58.465+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-03T19:16:58.465+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:16:58.487+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 19:05:54.497116+00:00
[2023-01-03T19:16:58.493+0000] {standard_task_runner.py:55} INFO - Started process 2596 to run task
[2023-01-03T19:16:58.497+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T19:05:54.497116+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmpxcn8xy9t']
[2023-01-03T19:16:58.500+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask dashboard
[2023-01-03T19:16:58.588+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:05:54.497116+00:00 [running]> on host 321b86f85270
[2023-01-03T19:16:58.698+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T19:05:54.497116+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T19:05:54.497116+00:00
[2023-01-03T19:17:02.409+0000] {logging_mixin.py:137} INFO - Dash is running on http://127.0.0.1:8050/
[2023-01-03T19:17:02.409+0000] {dash.py:1968} INFO - Dash is running on http://127.0.0.1:8050/

[2023-01-03T19:17:02.417+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-03T19:17:02.418+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-03T19:17:02.419+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-03T19:17:02.419+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-03T19:17:02.447+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-03T19:17:02.477+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
